### ISSUE TITLE
Typo in the text

### ISSUE THREAD

**Issue by ahartikainen** [paul-buerkner/LFO-CV-paper#3]
Hi, I was reading the pre-print and noticed small typo in the conclusion section. I thought of raising an issue here so it won't go unnoticed.

https://github.com/paul-buerkner/LFO-CV-paper/blob/1be11db39f5cc591beb94576cd0022095d5906b8/LFO-CV.Rmd#L1030

"the comptutation time" --> "the computation time"

**Comment by paul-buerkner** [comment]
Thank you! Just fixed it. :-)
